name: Tag New Release

on:
  push:
    branches:
      - master
      - action-test

jobs:

  release:
    name: Release a new version

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.11
      env:
        WITH_V: true
        RELEASE_BRANCHES: action-test,master
