name: Tag New Release

on:
  push:
    branches:
      - master
      - action-test

jobs:

  tag:
    name: Tag New Release

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        WITH_V: true
        RELEASE_BRANCHES: action-test,master
