name: Update Version

on:
  push:
    branches:
      - master
      - action-test

jobs:

  tag:
    name: Tag new release 
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.11.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
